# Configuración de Nixpacks para Railway
# https://nixpacks.com/docs/configuration/file

# Proveedor y versión de Node.js
[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

# Instalar todas las dependencias incluyendo TypeScript
[phases.install]
cmds = [
  "npm ci --omit=dev",
  "cd backend && npm ci",
  "cd frontend && npm ci"
]

# Compilar backend y frontend
[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && npm run build"
]

# Variables de entorno necesarias para el build
[variables]
NODE_ENV = "production"

# Comando de inicio
[start]
cmd = "node backend/dist/server.js"