# Configuración de Nixpacks para Railway
# https://nixpacks.com/docs/configuration/file

# Proveedor y versión de Node.js
[phases.setup]
nixPkgs = ["nodejs-18_x"]

# Instalar dependencias y compilar en un solo paso
[phases.build]
cmds = [
  "echo '📦 Installing backend dependencies...'",
  "cd backend && npm install --production=false",
  "echo '🔨 Building backend...'",
  "npm run build",
  "echo '📦 Installing frontend dependencies...'",
  "cd ../frontend && npm install --production=false",
  "echo '🎨 Building frontend...'",
  "npm run build",
  "echo '✅ Build completed!'"
]

# Variables de entorno necesarias para el build
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

# Comando de inicio
[start]
cmd = "node backend/dist/server.js"