# Configuración de Nixpacks para Railway
# https://nixpacks.com/docs/configuration/file

# Proveedor y versión de Node.js
[phases.setup]
nixPkgs = ["nodejs-18_x"]

# Usar script de build optimizado
[phases.build]
cmds = ["chmod +x railway-build.sh && ./railway-build.sh"]

# Variables de entorno necesarias para el build
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

# Comando de inicio
[start]
cmd = "node backend/dist/server.js"