[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd backend && npm ci --production=false",
  "cd ../frontend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd ../frontend && npm run build",
  "mkdir -p ../backend/public",
  "cp -r ../frontend/dist/* ../backend/public/"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"