[build]
builder = "nixpacks"
buildCommand = "chmod +x railway-build.sh && ./railway-build.sh"

[deploy]
startCommand = "node backend/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"