[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install --production=false && npm run build && cd ../frontend && npm install --production=false && npm run build"

[deploy]
startCommand = "node backend/dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"